Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb06.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb07.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb08.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb09.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb16.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb17.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb18.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb19.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb26.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb27.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb28.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb29.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb36.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb37.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb38.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb39.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb46.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb47.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb48.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb49.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb56.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb57.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb58.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-tlxweb59.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-acvweb06.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-acvweb07.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-acvweb08.titlemax.com:8080/check/test.html | select StatusDescription
Invoke-WebRequest -UseBasicParsing -Uri http://prd-acvweb09.titlemax.com:8080/check/test.html | select StatusDescription

Read-Host -Prompt "Press ENTER to exit"